// Masking of sensitive values in the screenshots (and the values `check secrets` looks for).
//   masking.env       the application's local .env files: values of the keys whose name suggests a URL, a host, a
//                     tenant, a client, an account, an e-mail address, a user or a secret (SENSITIVE_KEY), longer
//                     than 6 characters, except those matching masking.exclude (default: localhost, 127.0.0.1)
//   masking.guid      GUIDs (8-4-4-4-12 hexadecimal)
//   masking.patterns  more JavaScript regular expressions
// In the page, every text node and every field value that matches is replaced by dots; then the `masks` targets
// of the capture are replaced entirely. Masking does not know production-only values: review every image.
import fs from "node:fs";
import path from "node:path";
import { locate, CaptureError, describeTarget } from "./actions.mjs";

export const DOTS = "••••••••";
export const GUID = "[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}";
/** Names of .env keys whose values are masked. */
const SENSITIVE_KEY =
  /URL|URI|HOST|DOMAIN|ENDPOINT|TENANT|CLIENT|AUDIENCE|ACCOUNT|EMAIL|MAIL|USER|LOGIN|SECRET|PASSWORD|PASSWD|PWD|TOKEN|KEY|DSN|CONNECTION/i;
const MIN_LENGTH = 7;

/**
 * Entries of a .env text: KEY=value, `export KEY=value`, quoted values; comments and blank lines ignored.
 * @returns {Array<{ key: string, value: string, line: number }>}
 */
export function parseEnv(text) {
  const out = [];
  String(text)
    .split(/\r?\n/)
    .forEach((l, i) => {
      const m = /^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_.-]*)\s*=\s*(.*)$/.exec(l);
      if (!m) return;
      let v = m[2].trim();
      const q = /^(["'`])(.*)\1/.exec(v);
      v = q ? q[2] : v.replace(/\s+#.*$/, "").trim();
      out.push({ key: m[1], value: v, line: i + 1 });
    });
  return out;
}

/**
 * Sensitive values of the masking.env files (relative to the project root; missing files are skipped).
 * @returns {Array<{ key: string, value: string, file: string }>}
 */
export function sensitiveValues(root, masking) {
  const exclude = masking.exclude ? new RegExp(masking.exclude, "i") : null;
  const seen = new Set();
  const out = [];
  for (const f of masking.env || []) {
    const file = path.resolve(root, f);
    if (!fs.existsSync(file) || !fs.statSync(file).isFile()) continue;
    for (const { key, value } of parseEnv(fs.readFileSync(file, "utf8"))) {
      if (!SENSITIVE_KEY.test(key) || value.length < MIN_LENGTH || (exclude && exclude.test(value)) || seen.has(value))
        continue;
      seen.add(value);
      out.push({ key, value, file: f });
    }
  }
  return out;
}

const escapeRegex = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

/**
 * Source of the masking regular expression (flags "gi"), or null when there is nothing to mask.
 * Longest values first, so that a value containing another one is masked whole.
 */
export function maskSource(values, { guid = true, patterns = [] } = {}) {
  const parts = [...values]
    .map((v) => (typeof v === "string" ? v : v.value))
    .sort((a, b) => b.length - a.length)
    .map(escapeRegex);
  if (guid) parts.push(GUID);
  for (const p of patterns) parts.push(`(?:${p})`);
  return parts.length ? parts.join("|") : null;
}

/** Applies the masking regex to a text (used by the tests and by `check secrets`). */
export function maskText(text, source) {
  return source ? String(text).replace(new RegExp(source, "gi"), DOTS) : String(text);
}

/**
 * Runs in the page (one frame): replaces with `dots` every match of `source` in the text the frame shows, and
 * returns the number of replacements (SECURITY.md, "Masking has limits"). Looked at: the document and every OPEN
 * shadow root (a closed one cannot be read); text nodes; field values; the title, placeholder, alt, aria-label and
 * aria-description attributes; a value split across several elements (`jo<b>hn@acme</b>.com`: the smallest
 * element whose whole text holds it is masked whole); and the text generated by CSS (`content` of ::before and
 * ::after), overridden by a style rule.
 * @param {{ source: string, dots: string }} p
 */
function maskDocument({ source, dots }) {
  const re = new RegExp(source, "gi");
  const has = (s) => new RegExp(source, "i").test(s);
  let count = 0;
  const replace = (s) =>
    s.replace(re, () => {
      count++;
      return dots;
    });
  const SKIP = new Set(["SCRIPT", "STYLE", "NOSCRIPT", "TEMPLATE"]);
  const ATTRIBUTES = ["title", "placeholder", "alt", "aria-label", "aria-description"];

  /** Text nodes, one by one. */
  function maskTextNodes(top) {
    const walker = document.createTreeWalker(top, NodeFilter.SHOW_TEXT);
    while (walker.nextNode()) {
      const node = walker.currentNode;
      if (node.parentElement && SKIP.has(node.parentElement.tagName)) continue;
      const v = replace(node.nodeValue);
      if (v !== node.nodeValue) node.nodeValue = v;
    }
  }
  /** Field values and the attributes a screenshot can show (a tooltip, a broken image's text…). */
  function maskFieldsAndAttributes(root) {
    for (const node of root.querySelectorAll("input, textarea")) {
      const el = /** @type {HTMLInputElement} */ (node);
      if (!el.value) continue;
      const v = replace(el.value);
      if (v !== el.value) el.value = v;
    }
    for (const el of root.querySelectorAll(ATTRIBUTES.map((a) => `[${a}]`).join(",")))
      for (const a of ATTRIBUTES) {
        const old = el.getAttribute(a);
        const v = old === null ? old : replace(old);
        if (v !== old) el.setAttribute(a, v);
      }
  }
  /**
   * A value split across elements: no text node holds it, their element does. The smallest such element is
   * masked whole (its inner markup is lost: it is only a screenshot).
   */
  function maskSplitText(elements) {
    for (let round = 0; round < 50; round++) {
      const split = elements().filter(
        (el) => !SKIP.has(el.tagName) && has(el.textContent) && ![...el.children].some((c) => has(c.textContent)),
      );
      if (!split.length) return;
      for (const el of split) el.textContent = replace(el.textContent);
    }
  }
  /** Text generated by CSS (content of ::before / ::after): overridden by a style rule. */
  function maskGeneratedText(elements, root) {
    const rules = new Set();
    for (const el of elements())
      for (const pseudo of ["before", "after"]) {
        const content = getComputedStyle(el, `::${pseudo}`).content;
        if (!content || content === "none" || content === "normal" || !has(content)) continue;
        el.setAttribute(`data-doc-kit-mask-${pseudo}`, "");
        rules.add(pseudo);
        count++;
      }
    if (!rules.size) return;
    const style = document.createElement("style");
    style.textContent = [...rules]
      .map((p) => `[data-doc-kit-mask-${p}]::${p}{content:${JSON.stringify(dots)} !important}`)
      .join("\n");
    (root === document ? document.head || document.body : root).appendChild(style);
  }

  /** @type {Array<Document|ShadowRoot>} */
  const roots = [];
  const visit = (root) => {
    roots.push(root);
    for (const el of root.querySelectorAll("*")) if (el.shadowRoot) visit(el.shadowRoot);
  };
  visit(document);
  for (const root of roots) {
    const top = root === document ? document.body : root;
    if (!top) continue;
    const elements = () => [...(root === document ? [document.body] : []), ...top.querySelectorAll("*")];
    maskTextNodes(top);
    maskFieldsAndAttributes(root);
    maskSplitText(elements);
    maskGeneratedText(elements, root);
  }
  return count;
}

/**
 * Masks the page: in every frame, the text matching `source` (maskDocument), then the `masks` targets. A target that
 * matches nothing is an error (CaptureError "maskMissing"), unless `required` is false (the second pass, just
 * before the shot).
 * @returns {Promise<number>} number of replacements in the text
 */
export async function maskPage(page, { source, masks = [], selectors = {}, required = true }) {
  let n = 0;
  if (source)
    // Every frame (iframes included, whatever their origin): a frame the page shows is in the screenshot.
    for (const frame of page.frames()) {
      try {
        n += await frame.evaluate(maskDocument, { source, dots: DOTS });
      } catch (e) {
        if (!frame.isDetached()) throw e; // a frame removed meanwhile is not in the screenshot
      }
    }
  // Every match of a mask target (unless it names one with nth or last).
  // A mask target that matches nothing is an error, never a silent pass: what it should hide would be shown
  // (ETUDE-CAPTURES.md C1).
  for (const t of masks) {
    const found = locate(page, t, selectors, page, { all: true });
    if ((await found.count()) === 0) {
      // The second pass, just before the shot: a target located by its text is already dots.
      if (!required) continue;
      throw new CaptureError("maskMissing", { target: describeTarget(t) });
    }
    await found.evaluateAll((els, dots) => {
      for (const el of els) {
        if ("value" in el && el.tagName !== "BUTTON") el.value = dots;
        else el.textContent = dots;
      }
    }, DOTS);
  }
  return n;
}
