// Layout check: opens EVERY page of the built site and reports the tables that are wider than the reading
// column (horizontal scrolling means a squeezed or cut column). A table rendered by a directive (::facts,
// ::faits — marked data-generated by the Markdown engine) is never reported: the writer did not write it by
// hand and cannot fix its width, and a long nested path is already given break opportunities of its own
// (<wbr>, engine/build/markdown.mjs factsCell/render).
import { pathToFileURL } from "node:url";
import { launchBrowser } from "../project/browser.mjs";
import { waitForStable } from "../capture/stable.mjs";
import { TIMINGS } from "../capture/timings.mjs";

/**
 * @param {{ file: string, width?: number, topOfPage?: string }} p
 * @returns {Promise<{ pages: number, width: number, problems: Array<{page: string, heading: string, wide: number, visible: number}> }>}
 */
export async function checkTables({ file, width = 1440, topOfPage = "(top of page)" }) {
  const browser = await launchBrowser();
  try {
    const page = await (await browser.newContext({ viewport: { width, height: 900 } })).newPage();
    await page.goto(pathToFileURL(file).href);
    await waitForStable(page, { quietMs: TIMINGS.siteQuiet });
    const ids = await page.evaluate(() => JSON.parse(document.getElementById("donnees").textContent).ordre);
    const problems = [];
    for (const id of ids) {
      await page.evaluate((h) => (location.hash = h), "#/" + id);
      await waitForStable(page, { quietMs: TIMINGS.siteQuiet });
      const wide = await page.evaluate(
        (top) =>
          [...document.querySelectorAll(".contenu .tableau:not([data-generated])")]
            .filter((t) => t.scrollWidth > t.clientWidth + 2)
            .map((t) => {
              let h = t.previousElementSibling;
              while (h && !/^H[23]$/.test(h.tagName)) h = h.previousElementSibling;
              return { heading: h ? h.textContent.replace("#", "").trim() : top, wide: t.scrollWidth, visible: t.clientWidth };
            }),
        topOfPage
      );
      for (const w of wide) problems.push({ page: id, ...w });
    }
    return { pages: ids.length, width, problems };
  } finally {
    await browser.close();
  }
}
